---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bluebuild-andersns-desktop
description: Gaming + Hyprland + Nix development image based on Bazzite

# Base image: Bazzite includes Steam, MangoHud, Gamescope, gaming kernel
base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - from-file: modules/shared.yml
