#!/bin/bash
# Setup user configs on first Hyprland launch
# This runs via Hyprland's exec-once

MARKER_FILE="$HOME/.config/.skel-configs-copied"
RELOAD_HYPRLAND=false

# Create config directory if it doesn't exist
mkdir -p "$HOME/.config"

# ALWAYS ensure env.conf exists (required by hyprland.conf source directive)
if [ ! -f "$HOME/.config/hypr/env.conf" ] && [ -f "/usr/etc/skel/.config/hypr/env.conf" ]; then
    mkdir -p "$HOME/.config/hypr"
    cp /usr/etc/skel/.config/hypr/env.conf "$HOME/.config/hypr/env.conf"
fi

# ALWAYS check and replace Hyprland auto-generated config
if [ -d "/usr/etc/skel/.config/hypr" ]; then
    mkdir -p "$HOME/.config/hypr"
    
    # Check if config exists and if it's auto-generated
    if [ -f "$HOME/.config/hypr/hyprland.conf" ]; then
        if grep -q "autogenerated = 1" "$HOME/.config/hypr/hyprland.conf" 2>/dev/null; then
            # Replace auto-generated config with our custom one
            cp -r /usr/etc/skel/.config/hypr/* "$HOME/.config/hypr/"
            RELOAD_HYPRLAND=true
        fi
    elif [ ! -f "$HOME/.config/hypr/hyprland.conf" ]; then
        # No config exists, copy ours
        cp -r /usr/etc/skel/.config/hypr/* "$HOME/.config/hypr/"
        RELOAD_HYPRLAND=true
    fi
fi

# Skip other configs if already copied
if [ -f "$MARKER_FILE" ]; then
    if [ "$RELOAD_HYPRLAND" = true ]; then
        hyprctl reload
    fi
    exit 0
fi

# Copy Alacritty config if it doesn't exist
if [ ! -f "$HOME/.config/alacritty/alacritty.toml" ] && [ -d "/usr/etc/skel/.config/alacritty" ]; then
    mkdir -p "$HOME/.config/alacritty"
    cp -r /usr/etc/skel/.config/alacritty/* "$HOME/.config/alacritty/"
fi

# Copy Waybar config if it doesn't exist
if [ ! -d "$HOME/.config/waybar" ] && [ -d "/usr/etc/skel/.config/waybar" ]; then
    mkdir -p "$HOME/.config/waybar"
    cp -r /usr/etc/skel/.config/waybar/* "$HOME/.config/waybar/"
fi

# Copy Kitty config if it doesn't exist
if [ ! -f "$HOME/.config/kitty/kitty.conf" ] && [ -d "/usr/etc/skel/.config/kitty" ]; then
    mkdir -p "$HOME/.config/kitty"
    cp -r /usr/etc/skel/.config/kitty/* "$HOME/.config/kitty/"
fi

# Copy Foot config if it doesn't exist
if [ ! -f "$HOME/.config/foot/foot.ini" ] && [ -d "/usr/etc/skel/.config/foot" ]; then
    mkdir -p "$HOME/.config/foot"
    cp -r /usr/etc/skel/.config/foot/* "$HOME/.config/foot/"
fi

# Copy Wofi config if it doesn't exist
if [ ! -d "$HOME/.config/wofi" ] && [ -d "/usr/etc/skel/.config/wofi" ]; then
    mkdir -p "$HOME/.config/wofi"
    cp -r /usr/etc/skel/.config/wofi/* "$HOME/.config/wofi/"
fi

# Enable elephant service for Walker launcher
if command -v elephant &> /dev/null; then
    elephant service enable 2>/dev/null || true
fi

# Mark as completed
touch "$MARKER_FILE"

# Restart Hyprland to pick up the new config if needed
if [ "$RELOAD_HYPRLAND" = true ]; then
    hyprctl reload
fi
